---
-name: Configurar svr banco de dados
 hosts: db01

 user: vagrant
 become: yes
 vars_files:
   - vars_main.yml
 var:
   -dbname: "db01"
   -dbusername: "root"
   -dbpassword: "devopsmaonamassa"

 tasks: 
   - name: Configurar hosts lab ansibles
     lineinfile: line "{{item}}" path=/etc/hosts
     with_items:
       - 192.168.56.3 control-node
       - 192.168.56.4 app01
       - 192.168.56.5 db01
  
  roles:
    - configuracao-default-so
    - geerlingguy.mysql