Vagrant.configure("2") do |config|
 
  config.vm.box = "bento/centos-7.9"
  config.vm.hostname = "control-node"
  config.vm.network  "private_network", ip:"192.168.56.2"
  config.vm.synced_folder ".","/vagrant", type: "nfs", nfs_version: 4
  config.vm.provision "shell", path: "provision.sh"
  
end
